#include "Utility.h"
#include "GameDataExtern.h"
#include "AdjustableParameter.h"
#include "XMLGenerator.h"
#include "ComplexShip.h"
#include "ComplexShipTileClass.h"
#include "ComplexShipTileDefinition.h"
#include "CSLifeSupportTileDefinition.h"

#include "CSLifeSupportTile.h"
class ComplexShip;

// Default constructor
CSLifeSupportTile::CSLifeSupportTile(void)
{
	// Life support tiles do require simulation by default
	ActivateSimulation(Game::C_TILE_LIFESUPPORT_SIMULATION_INTERVAL);

	// Initialise default values for each life support property
	Gravity = AdjustableParameter<float>(0.0f, 20.0f, 9.8f, 9.8f, 1.0f);
	OxygenLevel = AdjustableParameter<Oxygen::Type>((Oxygen::Type)0, (Oxygen::Type)100, (Oxygen::Type)100, (Oxygen::Type)100, (Oxygen::Type)2);
	OxygenRange = AdjustableParameter<Oxygen::Type>((Oxygen::Type)10, (Oxygen::Type)30, (Oxygen::Type)20, (Oxygen::Type)20, (Oxygen::Type)1);

	// Life support systems begin at full effectivity
	m_effectivity = 1.0f;
	m_gravityrange = 0;
}

// Simulation method for this tile.  This method will only be called if m_requiressimulation == true
void CSLifeSupportTile::PerformTileSimulation(unsigned int delta_ms)
{
	// Parameter check
	if (!m_parent) return;

	// This tile will only function if it is sufficiently powered.  Also set the simulation flag; 
	// the tile will continue to be simulated until all values are at target levels
	if (IsPowered())
	{
		Gravity.Update(delta_ms);
		OxygenLevel.Update(delta_ms);

		SetTileSimulationRequired( !(Gravity.IsAtTarget() && OxygenLevel.IsAtTarget()) );
	}
	else
	{
		Gravity.UpdateTowardsTarget(0.0f, delta_ms);
		OxygenLevel.UpdateTowardsTarget(0.0f, delta_ms);

		SetTileSimulationRequired( Gravity.Value != 0.0f || OxygenLevel.Value != 0.0f );
	}

	OutputDebugString(concat("Simulation LS tile; Power level = ")(m_powerlevel)(", IsPowered = ")(IsPowered())(", oxygen output = ")(OxygenLevel.Value)(" with targat ")(OxygenLevel.Target)("\n").str().c_str());

	// Trigger an update of the parent environment based on this change
	m_parent->UpdateGravity();
	m_parent->UpdateOxygen();
}

// One of the primary tile methods, to return the percentage of Gravity.Value generated by this 
// system at a particular location in the environment
float CSLifeSupportTile::GetGravityPercentage(int x, int y, int z) const
{
	// We must have a valid definition reference to calculate gravity strength
	if (!m_lifesupportdef) return 0.0f;

	// Get the integer squared distance from this tile to the target location
	INTVECTOR3 diff = INTVECTOR3(m_elementlocation.x - x, m_elementlocation.y - y, m_elementlocation.z - z);
	int dist = (diff.x*diff.x + diff.y*diff.y + diff.z*diff.z);

	// Sqrt to get the closest integer distance.  Should be fast (lookup) as long as distsq is within the sqrt cache size
	dist = (int)fast_sqrt(dist);

	// Get the gravity percentage for this distance, modify by the current effectivity value and return
	return (m_lifesupportdef->GetGravityStrength(dist) * m_effectivity);
}

// Virtual method to read any class-specific data for this tile type
void CSLifeSupportTile::ReadClassSpecificXMLData(TiXmlElement *node)
{
	// TODO: Do this
}

// Apply the contents of the tile to its parent objects.  Called upon linking, plus on repair of the ship.  Inherited virtual.
void CSLifeSupportTile::ApplyTileSpecific(void)
{

}

// Virtual inherited method to make a copy of this tile and return it
ComplexShipTile *CSLifeSupportTile::Copy(void) const
{
	// Call the copy constructor, which will in turn call the base class copy constructor, to create a copy of this tile
	return new CSLifeSupportTile(*this);
}

// Copy constructor
CSLifeSupportTile::CSLifeSupportTile(const CSLifeSupportTile &C) : ComplexShipTile(C)
{
	/* Copy class-specific properties here */

	// Copy the reference to this tile's class definition
	m_lifesupportdef = C.GetLifeSupportTileDefinition();

	// Copy all life support properties
	Gravity = C.Gravity;
	OxygenLevel = C.OxygenLevel;
	OxygenRange = C.OxygenRange;
	m_gravityrange = C.GetGravityRange();
	m_effectivity = C.GetEffectivity();
}

// Default destructor
CSLifeSupportTile::~CSLifeSupportTile(void)
{
}


// Static class method to generate XML data for a life support tile
TiXmlElement *CSLifeSupportTile::GenerateXML(void)
{
	// Create a new node to hold this data
	TiXmlElement *node = new TiXmlElement(D::NODE_ComplexShipTile);
	node->SetAttribute("code", m_definition->GetCode().c_str());

	// First, have the base class generate XML for all common tile properties
	TiXmlElement *base = ComplexShipTile::GenerateBaseClassXML(this);
	if (!base) { delete node; return NULL; }
	node->LinkEndChild(base);

	// Now generate XML for all properties specific to this tile class
	/* No tile-specific properties right now */
	// TODO: NOT TRUE

	// Return a reference to the new node
	return node;
}